// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: factor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FactorService_ComputeFactor_FullMethodName      = "/quantflow.FactorService/ComputeFactor"
	FactorService_ComputeFactorBatch_FullMethodName = "/quantflow.FactorService/ComputeFactorBatch"
	FactorService_ListFactors_FullMethodName        = "/quantflow.FactorService/ListFactors"
)

// FactorServiceClient is the client API for FactorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FactorService provides alpha factor computation capabilities.
// Factors are computed in Python using pandas/numpy and returned as protobuf messages.
type FactorServiceClient interface {
	// Compute a single factor for a universe of symbols.
	ComputeFactor(ctx context.Context, in *ComputeFactorRequest, opts ...grpc.CallOption) (*ComputeFactorResponse, error)
	// Compute multiple factors in one batch call.
	ComputeFactorBatch(ctx context.Context, in *ComputeFactorBatchRequest, opts ...grpc.CallOption) (*ComputeFactorBatchResponse, error)
	// List all available factors with metadata.
	ListFactors(ctx context.Context, in *ListFactorsRequest, opts ...grpc.CallOption) (*ListFactorsResponse, error)
}

type factorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFactorServiceClient(cc grpc.ClientConnInterface) FactorServiceClient {
	return &factorServiceClient{cc}
}

func (c *factorServiceClient) ComputeFactor(ctx context.Context, in *ComputeFactorRequest, opts ...grpc.CallOption) (*ComputeFactorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeFactorResponse)
	err := c.cc.Invoke(ctx, FactorService_ComputeFactor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *factorServiceClient) ComputeFactorBatch(ctx context.Context, in *ComputeFactorBatchRequest, opts ...grpc.CallOption) (*ComputeFactorBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeFactorBatchResponse)
	err := c.cc.Invoke(ctx, FactorService_ComputeFactorBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *factorServiceClient) ListFactors(ctx context.Context, in *ListFactorsRequest, opts ...grpc.CallOption) (*ListFactorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFactorsResponse)
	err := c.cc.Invoke(ctx, FactorService_ListFactors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FactorServiceServer is the server API for FactorService service.
// All implementations must embed UnimplementedFactorServiceServer
// for forward compatibility.
//
// FactorService provides alpha factor computation capabilities.
// Factors are computed in Python using pandas/numpy and returned as protobuf messages.
type FactorServiceServer interface {
	// Compute a single factor for a universe of symbols.
	ComputeFactor(context.Context, *ComputeFactorRequest) (*ComputeFactorResponse, error)
	// Compute multiple factors in one batch call.
	ComputeFactorBatch(context.Context, *ComputeFactorBatchRequest) (*ComputeFactorBatchResponse, error)
	// List all available factors with metadata.
	ListFactors(context.Context, *ListFactorsRequest) (*ListFactorsResponse, error)
	mustEmbedUnimplementedFactorServiceServer()
}

// UnimplementedFactorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFactorServiceServer struct{}

func (UnimplementedFactorServiceServer) ComputeFactor(context.Context, *ComputeFactorRequest) (*ComputeFactorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputeFactor not implemented")
}
func (UnimplementedFactorServiceServer) ComputeFactorBatch(context.Context, *ComputeFactorBatchRequest) (*ComputeFactorBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ComputeFactorBatch not implemented")
}
func (UnimplementedFactorServiceServer) ListFactors(context.Context, *ListFactorsRequest) (*ListFactorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFactors not implemented")
}
func (UnimplementedFactorServiceServer) mustEmbedUnimplementedFactorServiceServer() {}
func (UnimplementedFactorServiceServer) testEmbeddedByValue()                       {}

// UnsafeFactorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FactorServiceServer will
// result in compilation errors.
type UnsafeFactorServiceServer interface {
	mustEmbedUnimplementedFactorServiceServer()
}

func RegisterFactorServiceServer(s grpc.ServiceRegistrar, srv FactorServiceServer) {
	// If the following call panics, it indicates UnimplementedFactorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FactorService_ServiceDesc, srv)
}

func _FactorService_ComputeFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeFactorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactorServiceServer).ComputeFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FactorService_ComputeFactor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactorServiceServer).ComputeFactor(ctx, req.(*ComputeFactorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FactorService_ComputeFactorBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeFactorBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactorServiceServer).ComputeFactorBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FactorService_ComputeFactorBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactorServiceServer).ComputeFactorBatch(ctx, req.(*ComputeFactorBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FactorService_ListFactors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFactorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FactorServiceServer).ListFactors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FactorService_ListFactors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FactorServiceServer).ListFactors(ctx, req.(*ListFactorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FactorService_ServiceDesc is the grpc.ServiceDesc for FactorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FactorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quantflow.FactorService",
	HandlerType: (*FactorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeFactor",
			Handler:    _FactorService_ComputeFactor_Handler,
		},
		{
			MethodName: "ComputeFactorBatch",
			Handler:    _FactorService_ComputeFactorBatch_Handler,
		},
		{
			MethodName: "ListFactors",
			Handler:    _FactorService_ListFactors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "factor.proto",
}
