// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: factor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeFactorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactorName    string                 `protobuf:"bytes,1,opt,name=factor_name,json=factorName,proto3" json:"factor_name,omitempty"`
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OhlcvData     []byte                 `protobuf:"bytes,6,opt,name=ohlcv_data,json=ohlcvData,proto3" json:"ohlcv_data,omitempty"` // Arrow IPC bytes (zero-copy DataFrame transfer)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeFactorRequest) Reset() {
	*x = ComputeFactorRequest{}
	mi := &file_factor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeFactorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeFactorRequest) ProtoMessage() {}

func (x *ComputeFactorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_factor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeFactorRequest.ProtoReflect.Descriptor instead.
func (*ComputeFactorRequest) Descriptor() ([]byte, []int) {
	return file_factor_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeFactorRequest) GetFactorName() string {
	if x != nil {
		return x.FactorName
	}
	return ""
}

func (x *ComputeFactorRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ComputeFactorRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ComputeFactorRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ComputeFactorRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ComputeFactorRequest) GetOhlcvData() []byte {
	if x != nil {
		return x.OhlcvData
	}
	return nil
}

type FactorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Dates         []string               `protobuf:"bytes,2,rep,name=dates,proto3" json:"dates,omitempty"`
	Values        []float64              `protobuf:"fixed64,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorResult) Reset() {
	*x = FactorResult{}
	mi := &file_factor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorResult) ProtoMessage() {}

func (x *FactorResult) ProtoReflect() protoreflect.Message {
	mi := &file_factor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorResult.ProtoReflect.Descriptor instead.
func (*FactorResult) Descriptor() ([]byte, []int) {
	return file_factor_proto_rawDescGZIP(), []int{1}
}

func (x *FactorResult) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FactorResult) GetDates() []string {
	if x != nil {
		return x.Dates
	}
	return nil
}

func (x *FactorResult) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type ComputeFactorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactorName    string                 `protobuf:"bytes,1,opt,name=factor_name,json=factorName,proto3" json:"factor_name,omitempty"`
	Results       []*FactorResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	ComputeTimeMs int64                  `protobuf:"varint,3,opt,name=compute_time_ms,json=computeTimeMs,proto3" json:"compute_time_ms,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeFactorResponse) Reset() {
	*x = ComputeFactorResponse{}
	mi := &file_factor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeFactorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeFactorResponse) ProtoMessage() {}

func (x *ComputeFactorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_factor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeFactorResponse.ProtoReflect.Descriptor instead.
func (*ComputeFactorResponse) Descriptor() ([]byte, []int) {
	return file_factor_proto_rawDescGZIP(), []int{2}
}

func (x *ComputeFactorResponse) GetFactorName() string {
	if x != nil {
		return x.FactorName
	}
	return ""
}

func (x *ComputeFactorResponse) GetResults() []*FactorResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ComputeFactorResponse) GetComputeTimeMs() int64 {
	if x != nil {
		return x.ComputeTimeMs
	}
	return 0
}

func (x *ComputeFactorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ComputeFactorBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FactorNames   []string               `protobuf:"bytes,1,rep,name=factor_names,json=factorNames,proto3" json:"factor_names,omitempty"`
	Symbols       []string               `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OhlcvData     []byte                 `protobuf:"bytes,6,opt,name=ohlcv_data,json=ohlcvData,proto3" json:"ohlcv_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeFactorBatchRequest) Reset() {
	*x = ComputeFactorBatchRequest{}
	mi := &file_factor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeFactorBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeFactorBatchRequest) ProtoMessage() {}

func (x *ComputeFactorBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_factor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeFactorBatchRequest.ProtoReflect.Descriptor instead.
func (*ComputeFactorBatchRequest) Descriptor() ([]byte, []int) {
	return file_factor_proto_rawDescGZIP(), []int{3}
}

func (x *ComputeFactorBatchRequest) GetFactorNames() []string {
	if x != nil {
		return x.FactorNames
	}
	return nil
}

func (x *ComputeFactorBatchRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ComputeFactorBatchRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ComputeFactorBatchRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ComputeFactorBatchRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ComputeFactorBatchRequest) GetOhlcvData() []byte {
	if x != nil {
		return x.OhlcvData
	}
	return nil
}

type ComputeFactorBatchResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	FactorResponses    []*ComputeFactorResponse `protobuf:"bytes,1,rep,name=factor_responses,json=factorResponses,proto3" json:"factor_responses,omitempty"`
	TotalComputeTimeMs int64                    `protobuf:"varint,2,opt,name=total_compute_time_ms,json=totalComputeTimeMs,proto3" json:"total_compute_time_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComputeFactorBatchResponse) Reset() {
	*x = ComputeFactorBatchResponse{}
	mi := &file_factor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeFactorBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeFactorBatchResponse) ProtoMessage() {}

func (x *ComputeFactorBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_factor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeFactorBatchResponse.ProtoReflect.Descriptor instead.
func (*ComputeFactorBatchResponse) Descriptor() ([]byte, []int) {
	return file_factor_proto_rawDescGZIP(), []int{4}
}

func (x *ComputeFactorBatchResponse) GetFactorResponses() []*ComputeFactorResponse {
	if x != nil {
		return x.FactorResponses
	}
	return nil
}

func (x *ComputeFactorBatchResponse) GetTotalComputeTimeMs() int64 {
	if x != nil {
		return x.TotalComputeTimeMs
	}
	return 0
}

type FactorMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultParams map[string]string      `protobuf:"bytes,4,rep,name=default_params,json=defaultParams,proto3" json:"default_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorMeta) Reset() {
	*x = FactorMeta{}
	mi := &file_factor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorMeta) ProtoMessage() {}

func (x *FactorMeta) ProtoReflect() protoreflect.Message {
	mi := &file_factor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorMeta.ProtoReflect.Descriptor instead.
func (*FactorMeta) Descriptor() ([]byte, []int) {
	return file_factor_proto_rawDescGZIP(), []int{5}
}

func (x *FactorMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FactorMeta) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FactorMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FactorMeta) GetDefaultParams() map[string]string {
	if x != nil {
		return x.DefaultParams
	}
	return nil
}

type ListFactorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFactorsRequest) Reset() {
	*x = ListFactorsRequest{}
	mi := &file_factor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFactorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFactorsRequest) ProtoMessage() {}

func (x *ListFactorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_factor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFactorsRequest.ProtoReflect.Descriptor instead.
func (*ListFactorsRequest) Descriptor() ([]byte, []int) {
	return file_factor_proto_rawDescGZIP(), []int{6}
}

type ListFactorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factors       []*FactorMeta          `protobuf:"bytes,1,rep,name=factors,proto3" json:"factors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFactorsResponse) Reset() {
	*x = ListFactorsResponse{}
	mi := &file_factor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFactorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFactorsResponse) ProtoMessage() {}

func (x *ListFactorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_factor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFactorsResponse.ProtoReflect.Descriptor instead.
func (*ListFactorsResponse) Descriptor() ([]byte, []int) {
	return file_factor_proto_rawDescGZIP(), []int{7}
}

func (x *ListFactorsResponse) GetFactors() []*FactorMeta {
	if x != nil {
		return x.Factors
	}
	return nil
}

var File_factor_proto protoreflect.FileDescriptor

const file_factor_proto_rawDesc = "" +
	"\n" +
	"\ffactor.proto\x12\tquantflow\"\xaa\x02\n" +
	"\x14ComputeFactorRequest\x12\x1f\n" +
	"\vfactor_name\x18\x01 \x01(\tR\n" +
	"factorName\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12C\n" +
	"\x06params\x18\x05 \x03(\v2+.quantflow.ComputeFactorRequest.ParamsEntryR\x06params\x12\x1d\n" +
	"\n" +
	"ohlcv_data\x18\x06 \x01(\fR\tohlcvData\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\fFactorResult\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05dates\x18\x02 \x03(\tR\x05dates\x12\x16\n" +
	"\x06values\x18\x03 \x03(\x01R\x06values\"\xa9\x01\n" +
	"\x15ComputeFactorResponse\x12\x1f\n" +
	"\vfactor_name\x18\x01 \x01(\tR\n" +
	"factorName\x121\n" +
	"\aresults\x18\x02 \x03(\v2\x17.quantflow.FactorResultR\aresults\x12&\n" +
	"\x0fcompute_time_ms\x18\x03 \x01(\x03R\rcomputeTimeMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xb6\x02\n" +
	"\x19ComputeFactorBatchRequest\x12!\n" +
	"\ffactor_names\x18\x01 \x03(\tR\vfactorNames\x12\x18\n" +
	"\asymbols\x18\x02 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12H\n" +
	"\x06params\x18\x05 \x03(\v20.quantflow.ComputeFactorBatchRequest.ParamsEntryR\x06params\x12\x1d\n" +
	"\n" +
	"ohlcv_data\x18\x06 \x01(\fR\tohlcvData\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x01\n" +
	"\x1aComputeFactorBatchResponse\x12K\n" +
	"\x10factor_responses\x18\x01 \x03(\v2 .quantflow.ComputeFactorResponseR\x0ffactorResponses\x121\n" +
	"\x15total_compute_time_ms\x18\x02 \x01(\x03R\x12totalComputeTimeMs\"\xf1\x01\n" +
	"\n" +
	"FactorMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12O\n" +
	"\x0edefault_params\x18\x04 \x03(\v2(.quantflow.FactorMeta.DefaultParamsEntryR\rdefaultParams\x1a@\n" +
	"\x12DefaultParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12ListFactorsRequest\"F\n" +
	"\x13ListFactorsResponse\x12/\n" +
	"\afactors\x18\x01 \x03(\v2\x15.quantflow.FactorMetaR\afactors2\x94\x02\n" +
	"\rFactorService\x12R\n" +
	"\rComputeFactor\x12\x1f.quantflow.ComputeFactorRequest\x1a .quantflow.ComputeFactorResponse\x12a\n" +
	"\x12ComputeFactorBatch\x12$.quantflow.ComputeFactorBatchRequest\x1a%.quantflow.ComputeFactorBatchResponse\x12L\n" +
	"\vListFactors\x12\x1d.quantflow.ListFactorsRequest\x1a\x1e.quantflow.ListFactorsResponseB'Z%quantflow/internal/python/proto;protob\x06proto3"

var (
	file_factor_proto_rawDescOnce sync.Once
	file_factor_proto_rawDescData []byte
)

func file_factor_proto_rawDescGZIP() []byte {
	file_factor_proto_rawDescOnce.Do(func() {
		file_factor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_factor_proto_rawDesc), len(file_factor_proto_rawDesc)))
	})
	return file_factor_proto_rawDescData
}

var file_factor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_factor_proto_goTypes = []any{
	(*ComputeFactorRequest)(nil),       // 0: quantflow.ComputeFactorRequest
	(*FactorResult)(nil),               // 1: quantflow.FactorResult
	(*ComputeFactorResponse)(nil),      // 2: quantflow.ComputeFactorResponse
	(*ComputeFactorBatchRequest)(nil),  // 3: quantflow.ComputeFactorBatchRequest
	(*ComputeFactorBatchResponse)(nil), // 4: quantflow.ComputeFactorBatchResponse
	(*FactorMeta)(nil),                 // 5: quantflow.FactorMeta
	(*ListFactorsRequest)(nil),         // 6: quantflow.ListFactorsRequest
	(*ListFactorsResponse)(nil),        // 7: quantflow.ListFactorsResponse
	nil,                                // 8: quantflow.ComputeFactorRequest.ParamsEntry
	nil,                                // 9: quantflow.ComputeFactorBatchRequest.ParamsEntry
	nil,                                // 10: quantflow.FactorMeta.DefaultParamsEntry
}
var file_factor_proto_depIdxs = []int32{
	8,  // 0: quantflow.ComputeFactorRequest.params:type_name -> quantflow.ComputeFactorRequest.ParamsEntry
	1,  // 1: quantflow.ComputeFactorResponse.results:type_name -> quantflow.FactorResult
	9,  // 2: quantflow.ComputeFactorBatchRequest.params:type_name -> quantflow.ComputeFactorBatchRequest.ParamsEntry
	2,  // 3: quantflow.ComputeFactorBatchResponse.factor_responses:type_name -> quantflow.ComputeFactorResponse
	10, // 4: quantflow.FactorMeta.default_params:type_name -> quantflow.FactorMeta.DefaultParamsEntry
	5,  // 5: quantflow.ListFactorsResponse.factors:type_name -> quantflow.FactorMeta
	0,  // 6: quantflow.FactorService.ComputeFactor:input_type -> quantflow.ComputeFactorRequest
	3,  // 7: quantflow.FactorService.ComputeFactorBatch:input_type -> quantflow.ComputeFactorBatchRequest
	6,  // 8: quantflow.FactorService.ListFactors:input_type -> quantflow.ListFactorsRequest
	2,  // 9: quantflow.FactorService.ComputeFactor:output_type -> quantflow.ComputeFactorResponse
	4,  // 10: quantflow.FactorService.ComputeFactorBatch:output_type -> quantflow.ComputeFactorBatchResponse
	7,  // 11: quantflow.FactorService.ListFactors:output_type -> quantflow.ListFactorsResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_factor_proto_init() }
func file_factor_proto_init() {
	if File_factor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_factor_proto_rawDesc), len(file_factor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_factor_proto_goTypes,
		DependencyIndexes: file_factor_proto_depIdxs,
		MessageInfos:      file_factor_proto_msgTypes,
	}.Build()
	File_factor_proto = out.File
	file_factor_proto_goTypes = nil
	file_factor_proto_depIdxs = nil
}
