// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: llm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLMChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // "openai/gpt-4o", "anthropic/claude-sonnet-4-6", etc.
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*LLMTool             `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`                                   // available tools with JSON Schema parameters
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"` // system-level instruction
	Temperature   float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`                     // 0.0–2.0, default 0.7
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`         // max completion tokens, 0 = provider default
	StreamId      string                 `protobuf:"bytes,7,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`             // correlation ID forwarded to frontend events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMChatRequest) Reset() {
	*x = LLMChatRequest{}
	mi := &file_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMChatRequest) ProtoMessage() {}

func (x *LLMChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMChatRequest.ProtoReflect.Descriptor instead.
func (*LLMChatRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{0}
}

func (x *LLMChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMChatRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *LLMChatRequest) GetTools() []*LLMTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *LLMChatRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *LLMChatRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *LLMChatRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMChatRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "system" | "user" | "assistant" | "tool"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"` // set when role="tool", links back to assistant tool_call
	ToolCalls     []*ToolCall            `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`      // set when role="assistant" and LLM wants to call tools
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ChatMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // unique ID for this tool call
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`           // capability name
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"` // JSON-encoded arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type LLMTool struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"` // JSON Schema for the tool's parameters
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LLMTool) Reset() {
	*x = LLMTool{}
	mi := &file_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMTool) ProtoMessage() {}

func (x *LLMTool) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMTool.ProtoReflect.Descriptor instead.
func (*LLMTool) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{3}
}

func (x *LLMTool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMTool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LLMTool) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

type LLMChatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeltaContent     string                 `protobuf:"bytes,1,opt,name=delta_content,json=deltaContent,proto3" json:"delta_content,omitempty"`              // incremental text token
	ToolCallDelta    *ToolCallDelta         `protobuf:"bytes,2,opt,name=tool_call_delta,json=toolCallDelta,proto3" json:"tool_call_delta,omitempty"`         // incremental tool call chunk
	FinishReason     string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`              // "stop" | "tool_calls" | "length" | "error"
	PromptTokens     int32                  `protobuf:"varint,4,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`             // set on final chunk only
	CompletionTokens int32                  `protobuf:"varint,5,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"` // set on final chunk only
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LLMChatResponse) Reset() {
	*x = LLMChatResponse{}
	mi := &file_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMChatResponse) ProtoMessage() {}

func (x *LLMChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMChatResponse.ProtoReflect.Descriptor instead.
func (*LLMChatResponse) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{4}
}

func (x *LLMChatResponse) GetDeltaContent() string {
	if x != nil {
		return x.DeltaContent
	}
	return ""
}

func (x *LLMChatResponse) GetToolCallDelta() *ToolCallDelta {
	if x != nil {
		return x.ToolCallDelta
	}
	return nil
}

func (x *LLMChatResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *LLMChatResponse) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *LLMChatResponse) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

type ToolCallDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                        // which tool call this delta belongs to
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                               // set on first chunk
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                           // set on first chunk
	ArgumentsDelta string                 `protobuf:"bytes,4,opt,name=arguments_delta,json=argumentsDelta,proto3" json:"arguments_delta,omitempty"` // incremental JSON fragment
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCallDelta) Reset() {
	*x = ToolCallDelta{}
	mi := &file_llm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDelta) ProtoMessage() {}

func (x *ToolCallDelta) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDelta.ProtoReflect.Descriptor instead.
func (*ToolCallDelta) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallDelta) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ToolCallDelta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallDelta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallDelta) GetArgumentsDelta() string {
	if x != nil {
		return x.ArgumentsDelta
	}
	return ""
}

type LLMListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMListModelsRequest) Reset() {
	*x = LLMListModelsRequest{}
	mi := &file_llm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMListModelsRequest) ProtoMessage() {}

func (x *LLMListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMListModelsRequest.ProtoReflect.Descriptor instead.
func (*LLMListModelsRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{6}
}

type LLMModelInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // "openai/gpt-4o"
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`                                 // "openai" | "anthropic" | "deepseek" | "ollama"
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`        // "GPT-4o"
	ContextWindow  int32                  `protobuf:"varint,4,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"` // max context tokens
	SupportsTools  bool                   `protobuf:"varint,5,opt,name=supports_tools,json=supportsTools,proto3" json:"supports_tools,omitempty"` // whether this model supports function calling
	SupportsVision bool                   `protobuf:"varint,6,opt,name=supports_vision,json=supportsVision,proto3" json:"supports_vision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LLMModelInfo) Reset() {
	*x = LLMModelInfo{}
	mi := &file_llm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMModelInfo) ProtoMessage() {}

func (x *LLMModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMModelInfo.ProtoReflect.Descriptor instead.
func (*LLMModelInfo) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{7}
}

func (x *LLMModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMModelInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMModelInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LLMModelInfo) GetContextWindow() int32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *LLMModelInfo) GetSupportsTools() bool {
	if x != nil {
		return x.SupportsTools
	}
	return false
}

func (x *LLMModelInfo) GetSupportsVision() bool {
	if x != nil {
		return x.SupportsVision
	}
	return false
}

type LLMListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*LLMModelInfo        `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMListModelsResponse) Reset() {
	*x = LLMListModelsResponse{}
	mi := &file_llm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMListModelsResponse) ProtoMessage() {}

func (x *LLMListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMListModelsResponse.ProtoReflect.Descriptor instead.
func (*LLMListModelsResponse) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{8}
}

func (x *LLMListModelsResponse) GetModels() []*LLMModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

type CountTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensRequest) Reset() {
	*x = CountTokensRequest{}
	mi := &file_llm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensRequest) ProtoMessage() {}

func (x *CountTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensRequest.ProtoReflect.Descriptor instead.
func (*CountTokensRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{9}
}

func (x *CountTokensRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CountTokensRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CountTokensRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

type CountTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenCount    int32                  `protobuf:"varint,1,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountTokensResponse) Reset() {
	*x = CountTokensResponse{}
	mi := &file_llm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountTokensResponse) ProtoMessage() {}

func (x *CountTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountTokensResponse.ProtoReflect.Descriptor instead.
func (*CountTokensResponse) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{10}
}

func (x *CountTokensResponse) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *CountTokensResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_llm_proto protoreflect.FileDescriptor

const file_llm_proto_rawDesc = "" +
	"\n" +
	"\tllm.proto\x12\tquantflow\"\x87\x02\n" +
	"\x0eLLMChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x122\n" +
	"\bmessages\x18\x02 \x03(\v2\x16.quantflow.ChatMessageR\bmessages\x12(\n" +
	"\x05tools\x18\x03 \x03(\v2\x12.quantflow.LLMToolR\x05tools\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12\x1b\n" +
	"\tstream_id\x18\a \x01(\tR\bstreamId\"\x91\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x122\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x13.quantflow.ToolCallR\ttoolCalls\"L\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"h\n" +
	"\aLLMTool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"\xef\x01\n" +
	"\x0fLLMChatResponse\x12#\n" +
	"\rdelta_content\x18\x01 \x01(\tR\fdeltaContent\x12@\n" +
	"\x0ftool_call_delta\x18\x02 \x01(\v2\x18.quantflow.ToolCallDeltaR\rtoolCallDelta\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\x12#\n" +
	"\rprompt_tokens\x18\x04 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x05 \x01(\x05R\x10completionTokens\"r\n" +
	"\rToolCallDelta\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x0farguments_delta\x18\x04 \x01(\tR\x0eargumentsDelta\"\x16\n" +
	"\x14LLMListModelsRequest\"\xd4\x01\n" +
	"\fLLMModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12%\n" +
	"\x0econtext_window\x18\x04 \x01(\x05R\rcontextWindow\x12%\n" +
	"\x0esupports_tools\x18\x05 \x01(\bR\rsupportsTools\x12'\n" +
	"\x0fsupports_vision\x18\x06 \x01(\bR\x0esupportsVision\"H\n" +
	"\x15LLMListModelsResponse\x12/\n" +
	"\x06models\x18\x01 \x03(\v2\x17.quantflow.LLMModelInfoR\x06models\"\x83\x01\n" +
	"\x12CountTokensRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x122\n" +
	"\bmessages\x18\x02 \x03(\v2\x16.quantflow.ChatMessageR\bmessages\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\"L\n" +
	"\x13CountTokensResponse\x12\x1f\n" +
	"\vtoken_count\x18\x01 \x01(\x05R\n" +
	"tokenCount\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xec\x01\n" +
	"\n" +
	"LLMService\x12?\n" +
	"\x04Chat\x12\x19.quantflow.LLMChatRequest\x1a\x1a.quantflow.LLMChatResponse0\x01\x12O\n" +
	"\n" +
	"ListModels\x12\x1f.quantflow.LLMListModelsRequest\x1a .quantflow.LLMListModelsResponse\x12L\n" +
	"\vCountTokens\x12\x1d.quantflow.CountTokensRequest\x1a\x1e.quantflow.CountTokensResponseB'Z%quantflow/internal/python/proto;protob\x06proto3"

var (
	file_llm_proto_rawDescOnce sync.Once
	file_llm_proto_rawDescData []byte
)

func file_llm_proto_rawDescGZIP() []byte {
	file_llm_proto_rawDescOnce.Do(func() {
		file_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)))
	})
	return file_llm_proto_rawDescData
}

var file_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_llm_proto_goTypes = []any{
	(*LLMChatRequest)(nil),        // 0: quantflow.LLMChatRequest
	(*ChatMessage)(nil),           // 1: quantflow.ChatMessage
	(*ToolCall)(nil),              // 2: quantflow.ToolCall
	(*LLMTool)(nil),               // 3: quantflow.LLMTool
	(*LLMChatResponse)(nil),       // 4: quantflow.LLMChatResponse
	(*ToolCallDelta)(nil),         // 5: quantflow.ToolCallDelta
	(*LLMListModelsRequest)(nil),  // 6: quantflow.LLMListModelsRequest
	(*LLMModelInfo)(nil),          // 7: quantflow.LLMModelInfo
	(*LLMListModelsResponse)(nil), // 8: quantflow.LLMListModelsResponse
	(*CountTokensRequest)(nil),    // 9: quantflow.CountTokensRequest
	(*CountTokensResponse)(nil),   // 10: quantflow.CountTokensResponse
}
var file_llm_proto_depIdxs = []int32{
	1,  // 0: quantflow.LLMChatRequest.messages:type_name -> quantflow.ChatMessage
	3,  // 1: quantflow.LLMChatRequest.tools:type_name -> quantflow.LLMTool
	2,  // 2: quantflow.ChatMessage.tool_calls:type_name -> quantflow.ToolCall
	5,  // 3: quantflow.LLMChatResponse.tool_call_delta:type_name -> quantflow.ToolCallDelta
	7,  // 4: quantflow.LLMListModelsResponse.models:type_name -> quantflow.LLMModelInfo
	1,  // 5: quantflow.CountTokensRequest.messages:type_name -> quantflow.ChatMessage
	0,  // 6: quantflow.LLMService.Chat:input_type -> quantflow.LLMChatRequest
	6,  // 7: quantflow.LLMService.ListModels:input_type -> quantflow.LLMListModelsRequest
	9,  // 8: quantflow.LLMService.CountTokens:input_type -> quantflow.CountTokensRequest
	4,  // 9: quantflow.LLMService.Chat:output_type -> quantflow.LLMChatResponse
	8,  // 10: quantflow.LLMService.ListModels:output_type -> quantflow.LLMListModelsResponse
	10, // 11: quantflow.LLMService.CountTokens:output_type -> quantflow.CountTokensResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_llm_proto_init() }
func file_llm_proto_init() {
	if File_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_proto_goTypes,
		DependencyIndexes: file_llm_proto_depIdxs,
		MessageInfos:      file_llm_proto_msgTypes,
	}.Build()
	File_llm_proto = out.File
	file_llm_proto_goTypes = nil
	file_llm_proto_depIdxs = nil
}
