// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: ml.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ModelType       string                 `protobuf:"bytes,1,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Features        []byte                 `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`
	Targets         []byte                 `protobuf:"bytes,3,opt,name=targets,proto3" json:"targets,omitempty"`
	Hyperparams     map[string]string      `protobuf:"bytes,4,rep,name=hyperparams,proto3" json:"hyperparams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TargetType      string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	ForecastHorizon int32                  `protobuf:"varint,6,opt,name=forecast_horizon,json=forecastHorizon,proto3" json:"forecast_horizon,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{0}
}

func (x *TrainRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *TrainRequest) GetFeatures() []byte {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *TrainRequest) GetTargets() []byte {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *TrainRequest) GetHyperparams() map[string]string {
	if x != nil {
		return x.Hyperparams
	}
	return nil
}

func (x *TrainRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *TrainRequest) GetForecastHorizon() int32 {
	if x != nil {
		return x.ForecastHorizon
	}
	return 0
}

type TrainResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModelId           string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelBytes        []byte                 `protobuf:"bytes,2,opt,name=model_bytes,json=modelBytes,proto3" json:"model_bytes,omitempty"`
	ModelFilePath     string                 `protobuf:"bytes,3,opt,name=model_file_path,json=modelFilePath,proto3" json:"model_file_path,omitempty"`
	Metrics           map[string]float64     `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	TrainTimeMs       int64                  `protobuf:"varint,5,opt,name=train_time_ms,json=trainTimeMs,proto3" json:"train_time_ms,omitempty"`
	FeatureImportance []*FeatureImportance   `protobuf:"bytes,6,rep,name=feature_importance,json=featureImportance,proto3" json:"feature_importance,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{1}
}

func (x *TrainResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TrainResponse) GetModelBytes() []byte {
	if x != nil {
		return x.ModelBytes
	}
	return nil
}

func (x *TrainResponse) GetModelFilePath() string {
	if x != nil {
		return x.ModelFilePath
	}
	return ""
}

func (x *TrainResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TrainResponse) GetTrainTimeMs() int64 {
	if x != nil {
		return x.TrainTimeMs
	}
	return 0
}

func (x *TrainResponse) GetFeatureImportance() []*FeatureImportance {
	if x != nil {
		return x.FeatureImportance
	}
	return nil
}

type FeatureImportance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureName   string                 `protobuf:"bytes,1,opt,name=feature_name,json=featureName,proto3" json:"feature_name,omitempty"`
	Importance    float64                `protobuf:"fixed64,2,opt,name=importance,proto3" json:"importance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureImportance) Reset() {
	*x = FeatureImportance{}
	mi := &file_ml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureImportance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureImportance) ProtoMessage() {}

func (x *FeatureImportance) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureImportance.ProtoReflect.Descriptor instead.
func (*FeatureImportance) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureImportance) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *FeatureImportance) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Features      []byte                 `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_ml_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{3}
}

func (x *PredictRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PredictRequest) GetFeatures() []byte {
	if x != nil {
		return x.Features
	}
	return nil
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predictions   []float64              `protobuf:"fixed64,1,rep,packed,name=predictions,proto3" json:"predictions,omitempty"`
	PredictTimeMs int64                  `protobuf:"varint,2,opt,name=predict_time_ms,json=predictTimeMs,proto3" json:"predict_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_ml_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{4}
}

func (x *PredictResponse) GetPredictions() []float64 {
	if x != nil {
		return x.Predictions
	}
	return nil
}

func (x *PredictResponse) GetPredictTimeMs() int64 {
	if x != nil {
		return x.PredictTimeMs
	}
	return 0
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Features      []byte                 `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`
	Actuals       []byte                 `protobuf:"bytes,3,opt,name=actuals,proto3" json:"actuals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_ml_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluateRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EvaluateRequest) GetFeatures() []byte {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *EvaluateRequest) GetActuals() []byte {
	if x != nil {
		return x.Actuals
	}
	return nil
}

type EvaluateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metrics        map[string]float64     `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	EvaluateTimeMs int64                  `protobuf:"varint,2,opt,name=evaluate_time_ms,json=evaluateTimeMs,proto3" json:"evaluate_time_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_ml_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *EvaluateResponse) GetEvaluateTimeMs() int64 {
	if x != nil {
		return x.EvaluateTimeMs
	}
	return 0
}

type AlphaMiningRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseFactorNames []string               `protobuf:"bytes,1,rep,name=base_factor_names,json=baseFactorNames,proto3" json:"base_factor_names,omitempty"`
	FactorData      []byte                 `protobuf:"bytes,2,opt,name=factor_data,json=factorData,proto3" json:"factor_data,omitempty"`
	ReturnsData     []byte                 `protobuf:"bytes,3,opt,name=returns_data,json=returnsData,proto3" json:"returns_data,omitempty"`
	PopulationSize  int32                  `protobuf:"varint,4,opt,name=population_size,json=populationSize,proto3" json:"population_size,omitempty"`
	Generations     int32                  `protobuf:"varint,5,opt,name=generations,proto3" json:"generations,omitempty"`
	CrossoverRate   float64                `protobuf:"fixed64,6,opt,name=crossover_rate,json=crossoverRate,proto3" json:"crossover_rate,omitempty"`
	MutationRate    float64                `protobuf:"fixed64,7,opt,name=mutation_rate,json=mutationRate,proto3" json:"mutation_rate,omitempty"`
	FitnessMetric   string                 `protobuf:"bytes,8,opt,name=fitness_metric,json=fitnessMetric,proto3" json:"fitness_metric,omitempty"`
	TopK            int32                  `protobuf:"varint,9,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlphaMiningRequest) Reset() {
	*x = AlphaMiningRequest{}
	mi := &file_ml_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlphaMiningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlphaMiningRequest) ProtoMessage() {}

func (x *AlphaMiningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlphaMiningRequest.ProtoReflect.Descriptor instead.
func (*AlphaMiningRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{7}
}

func (x *AlphaMiningRequest) GetBaseFactorNames() []string {
	if x != nil {
		return x.BaseFactorNames
	}
	return nil
}

func (x *AlphaMiningRequest) GetFactorData() []byte {
	if x != nil {
		return x.FactorData
	}
	return nil
}

func (x *AlphaMiningRequest) GetReturnsData() []byte {
	if x != nil {
		return x.ReturnsData
	}
	return nil
}

func (x *AlphaMiningRequest) GetPopulationSize() int32 {
	if x != nil {
		return x.PopulationSize
	}
	return 0
}

func (x *AlphaMiningRequest) GetGenerations() int32 {
	if x != nil {
		return x.Generations
	}
	return 0
}

func (x *AlphaMiningRequest) GetCrossoverRate() float64 {
	if x != nil {
		return x.CrossoverRate
	}
	return 0
}

func (x *AlphaMiningRequest) GetMutationRate() float64 {
	if x != nil {
		return x.MutationRate
	}
	return 0
}

func (x *AlphaMiningRequest) GetFitnessMetric() string {
	if x != nil {
		return x.FitnessMetric
	}
	return ""
}

func (x *AlphaMiningRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type AlphaMiningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factors       []*DiscoveredFactor    `protobuf:"bytes,1,rep,name=factors,proto3" json:"factors,omitempty"`
	MiningTimeMs  int64                  `protobuf:"varint,2,opt,name=mining_time_ms,json=miningTimeMs,proto3" json:"mining_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlphaMiningResponse) Reset() {
	*x = AlphaMiningResponse{}
	mi := &file_ml_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlphaMiningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlphaMiningResponse) ProtoMessage() {}

func (x *AlphaMiningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlphaMiningResponse.ProtoReflect.Descriptor instead.
func (*AlphaMiningResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{8}
}

func (x *AlphaMiningResponse) GetFactors() []*DiscoveredFactor {
	if x != nil {
		return x.Factors
	}
	return nil
}

func (x *AlphaMiningResponse) GetMiningTimeMs() int64 {
	if x != nil {
		return x.MiningTimeMs
	}
	return 0
}

type DiscoveredFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formula       string                 `protobuf:"bytes,1,opt,name=formula,proto3" json:"formula,omitempty"`
	Ic            float64                `protobuf:"fixed64,2,opt,name=ic,proto3" json:"ic,omitempty"`
	Ir            float64                `protobuf:"fixed64,3,opt,name=ir,proto3" json:"ir,omitempty"`
	Sharpe        float64                `protobuf:"fixed64,4,opt,name=sharpe,proto3" json:"sharpe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveredFactor) Reset() {
	*x = DiscoveredFactor{}
	mi := &file_ml_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveredFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveredFactor) ProtoMessage() {}

func (x *DiscoveredFactor) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveredFactor.ProtoReflect.Descriptor instead.
func (*DiscoveredFactor) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoveredFactor) GetFormula() string {
	if x != nil {
		return x.Formula
	}
	return ""
}

func (x *DiscoveredFactor) GetIc() float64 {
	if x != nil {
		return x.Ic
	}
	return 0
}

func (x *DiscoveredFactor) GetIr() float64 {
	if x != nil {
		return x.Ir
	}
	return 0
}

func (x *DiscoveredFactor) GetSharpe() float64 {
	if x != nil {
		return x.Sharpe
	}
	return 0
}

type RLTrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Hyperparams   map[string]string      `protobuf:"bytes,2,rep,name=hyperparams,proto3" json:"hyperparams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OhlcvData     []byte                 `protobuf:"bytes,3,opt,name=ohlcv_data,json=ohlcvData,proto3" json:"ohlcv_data,omitempty"`
	TotalEpisodes int32                  `protobuf:"varint,4,opt,name=total_episodes,json=totalEpisodes,proto3" json:"total_episodes,omitempty"`
	EpisodeLength int32                  `protobuf:"varint,5,opt,name=episode_length,json=episodeLength,proto3" json:"episode_length,omitempty"`
	ActionSpace   string                 `protobuf:"bytes,6,opt,name=action_space,json=actionSpace,proto3" json:"action_space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RLTrainRequest) Reset() {
	*x = RLTrainRequest{}
	mi := &file_ml_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RLTrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RLTrainRequest) ProtoMessage() {}

func (x *RLTrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RLTrainRequest.ProtoReflect.Descriptor instead.
func (*RLTrainRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{10}
}

func (x *RLTrainRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RLTrainRequest) GetHyperparams() map[string]string {
	if x != nil {
		return x.Hyperparams
	}
	return nil
}

func (x *RLTrainRequest) GetOhlcvData() []byte {
	if x != nil {
		return x.OhlcvData
	}
	return nil
}

func (x *RLTrainRequest) GetTotalEpisodes() int32 {
	if x != nil {
		return x.TotalEpisodes
	}
	return 0
}

func (x *RLTrainRequest) GetEpisodeLength() int32 {
	if x != nil {
		return x.EpisodeLength
	}
	return 0
}

func (x *RLTrainRequest) GetActionSpace() string {
	if x != nil {
		return x.ActionSpace
	}
	return ""
}

type RLTrainUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episode       int32                  `protobuf:"varint,1,opt,name=episode,proto3" json:"episode,omitempty"`
	Reward        float64                `protobuf:"fixed64,2,opt,name=reward,proto3" json:"reward,omitempty"`
	Sharpe        float64                `protobuf:"fixed64,3,opt,name=sharpe,proto3" json:"sharpe,omitempty"`
	Epsilon       float64                `protobuf:"fixed64,4,opt,name=epsilon,proto3" json:"epsilon,omitempty"`
	Steps         int32                  `protobuf:"varint,5,opt,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RLTrainUpdate) Reset() {
	*x = RLTrainUpdate{}
	mi := &file_ml_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RLTrainUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RLTrainUpdate) ProtoMessage() {}

func (x *RLTrainUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RLTrainUpdate.ProtoReflect.Descriptor instead.
func (*RLTrainUpdate) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{11}
}

func (x *RLTrainUpdate) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *RLTrainUpdate) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *RLTrainUpdate) GetSharpe() float64 {
	if x != nil {
		return x.Sharpe
	}
	return 0
}

func (x *RLTrainUpdate) GetEpsilon() float64 {
	if x != nil {
		return x.Epsilon
	}
	return 0
}

func (x *RLTrainUpdate) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

type RLPredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Observation   []byte                 `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RLPredictRequest) Reset() {
	*x = RLPredictRequest{}
	mi := &file_ml_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RLPredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RLPredictRequest) ProtoMessage() {}

func (x *RLPredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RLPredictRequest.ProtoReflect.Descriptor instead.
func (*RLPredictRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{12}
}

func (x *RLPredictRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RLPredictRequest) GetObservation() []byte {
	if x != nil {
		return x.Observation
	}
	return nil
}

type RLPredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        int32                  `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	ActionValue   float64                `protobuf:"fixed64,2,opt,name=action_value,json=actionValue,proto3" json:"action_value,omitempty"`
	ActionProbs   map[string]float64     `protobuf:"bytes,3,rep,name=action_probs,json=actionProbs,proto3" json:"action_probs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RLPredictResponse) Reset() {
	*x = RLPredictResponse{}
	mi := &file_ml_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RLPredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RLPredictResponse) ProtoMessage() {}

func (x *RLPredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RLPredictResponse.ProtoReflect.Descriptor instead.
func (*RLPredictResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{13}
}

func (x *RLPredictResponse) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *RLPredictResponse) GetActionValue() float64 {
	if x != nil {
		return x.ActionValue
	}
	return 0
}

func (x *RLPredictResponse) GetActionProbs() map[string]float64 {
	if x != nil {
		return x.ActionProbs
	}
	return nil
}

type RiskModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelType     string                 `protobuf:"bytes,1,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	ReturnsData   []byte                 `protobuf:"bytes,2,opt,name=returns_data,json=returnsData,proto3" json:"returns_data,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskModelRequest) Reset() {
	*x = RiskModelRequest{}
	mi := &file_ml_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskModelRequest) ProtoMessage() {}

func (x *RiskModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskModelRequest.ProtoReflect.Descriptor instead.
func (*RiskModelRequest) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{14}
}

func (x *RiskModelRequest) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *RiskModelRequest) GetReturnsData() []byte {
	if x != nil {
		return x.ReturnsData
	}
	return nil
}

func (x *RiskModelRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type RiskModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultData    []byte                 `protobuf:"bytes,1,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ComputeTimeMs int64                  `protobuf:"varint,3,opt,name=compute_time_ms,json=computeTimeMs,proto3" json:"compute_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskModelResponse) Reset() {
	*x = RiskModelResponse{}
	mi := &file_ml_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskModelResponse) ProtoMessage() {}

func (x *RiskModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskModelResponse.ProtoReflect.Descriptor instead.
func (*RiskModelResponse) Descriptor() ([]byte, []int) {
	return file_ml_proto_rawDescGZIP(), []int{15}
}

func (x *RiskModelResponse) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *RiskModelResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *RiskModelResponse) GetComputeTimeMs() int64 {
	if x != nil {
		return x.ComputeTimeMs
	}
	return 0
}

var File_ml_proto protoreflect.FileDescriptor

const file_ml_proto_rawDesc = "" +
	"\n" +
	"\bml.proto\x12\tquantflow\"\xbb\x02\n" +
	"\fTrainRequest\x12\x1d\n" +
	"\n" +
	"model_type\x18\x01 \x01(\tR\tmodelType\x12\x1a\n" +
	"\bfeatures\x18\x02 \x01(\fR\bfeatures\x12\x18\n" +
	"\atargets\x18\x03 \x01(\fR\atargets\x12J\n" +
	"\vhyperparams\x18\x04 \x03(\v2(.quantflow.TrainRequest.HyperparamsEntryR\vhyperparams\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12)\n" +
	"\x10forecast_horizon\x18\x06 \x01(\x05R\x0fforecastHorizon\x1a>\n" +
	"\x10HyperparamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x02\n" +
	"\rTrainResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1f\n" +
	"\vmodel_bytes\x18\x02 \x01(\fR\n" +
	"modelBytes\x12&\n" +
	"\x0fmodel_file_path\x18\x03 \x01(\tR\rmodelFilePath\x12?\n" +
	"\ametrics\x18\x04 \x03(\v2%.quantflow.TrainResponse.MetricsEntryR\ametrics\x12\"\n" +
	"\rtrain_time_ms\x18\x05 \x01(\x03R\vtrainTimeMs\x12K\n" +
	"\x12feature_importance\x18\x06 \x03(\v2\x1c.quantflow.FeatureImportanceR\x11featureImportance\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"V\n" +
	"\x11FeatureImportance\x12!\n" +
	"\ffeature_name\x18\x01 \x01(\tR\vfeatureName\x12\x1e\n" +
	"\n" +
	"importance\x18\x02 \x01(\x01R\n" +
	"importance\"G\n" +
	"\x0ePredictRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1a\n" +
	"\bfeatures\x18\x02 \x01(\fR\bfeatures\"[\n" +
	"\x0fPredictResponse\x12 \n" +
	"\vpredictions\x18\x01 \x03(\x01R\vpredictions\x12&\n" +
	"\x0fpredict_time_ms\x18\x02 \x01(\x03R\rpredictTimeMs\"b\n" +
	"\x0fEvaluateRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1a\n" +
	"\bfeatures\x18\x02 \x01(\fR\bfeatures\x12\x18\n" +
	"\aactuals\x18\x03 \x01(\fR\aactuals\"\xbc\x01\n" +
	"\x10EvaluateResponse\x12B\n" +
	"\ametrics\x18\x01 \x03(\v2(.quantflow.EvaluateResponse.MetricsEntryR\ametrics\x12(\n" +
	"\x10evaluate_time_ms\x18\x02 \x01(\x03R\x0eevaluateTimeMs\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xd7\x02\n" +
	"\x12AlphaMiningRequest\x12*\n" +
	"\x11base_factor_names\x18\x01 \x03(\tR\x0fbaseFactorNames\x12\x1f\n" +
	"\vfactor_data\x18\x02 \x01(\fR\n" +
	"factorData\x12!\n" +
	"\freturns_data\x18\x03 \x01(\fR\vreturnsData\x12'\n" +
	"\x0fpopulation_size\x18\x04 \x01(\x05R\x0epopulationSize\x12 \n" +
	"\vgenerations\x18\x05 \x01(\x05R\vgenerations\x12%\n" +
	"\x0ecrossover_rate\x18\x06 \x01(\x01R\rcrossoverRate\x12#\n" +
	"\rmutation_rate\x18\a \x01(\x01R\fmutationRate\x12%\n" +
	"\x0efitness_metric\x18\b \x01(\tR\rfitnessMetric\x12\x13\n" +
	"\x05top_k\x18\t \x01(\x05R\x04topK\"r\n" +
	"\x13AlphaMiningResponse\x125\n" +
	"\afactors\x18\x01 \x03(\v2\x1b.quantflow.DiscoveredFactorR\afactors\x12$\n" +
	"\x0emining_time_ms\x18\x02 \x01(\x03R\fminingTimeMs\"d\n" +
	"\x10DiscoveredFactor\x12\x18\n" +
	"\aformula\x18\x01 \x01(\tR\aformula\x12\x0e\n" +
	"\x02ic\x18\x02 \x01(\x01R\x02ic\x12\x0e\n" +
	"\x02ir\x18\x03 \x01(\x01R\x02ir\x12\x16\n" +
	"\x06sharpe\x18\x04 \x01(\x01R\x06sharpe\"\xcc\x02\n" +
	"\x0eRLTrainRequest\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12L\n" +
	"\vhyperparams\x18\x02 \x03(\v2*.quantflow.RLTrainRequest.HyperparamsEntryR\vhyperparams\x12\x1d\n" +
	"\n" +
	"ohlcv_data\x18\x03 \x01(\fR\tohlcvData\x12%\n" +
	"\x0etotal_episodes\x18\x04 \x01(\x05R\rtotalEpisodes\x12%\n" +
	"\x0eepisode_length\x18\x05 \x01(\x05R\repisodeLength\x12!\n" +
	"\faction_space\x18\x06 \x01(\tR\vactionSpace\x1a>\n" +
	"\x10HyperparamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\rRLTrainUpdate\x12\x18\n" +
	"\aepisode\x18\x01 \x01(\x05R\aepisode\x12\x16\n" +
	"\x06reward\x18\x02 \x01(\x01R\x06reward\x12\x16\n" +
	"\x06sharpe\x18\x03 \x01(\x01R\x06sharpe\x12\x18\n" +
	"\aepsilon\x18\x04 \x01(\x01R\aepsilon\x12\x14\n" +
	"\x05steps\x18\x05 \x01(\x05R\x05steps\"O\n" +
	"\x10RLPredictRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12 \n" +
	"\vobservation\x18\x02 \x01(\fR\vobservation\"\xe0\x01\n" +
	"\x11RLPredictResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\x05R\x06action\x12!\n" +
	"\faction_value\x18\x02 \x01(\x01R\vactionValue\x12P\n" +
	"\faction_probs\x18\x03 \x03(\v2-.quantflow.RLPredictResponse.ActionProbsEntryR\vactionProbs\x1a>\n" +
	"\x10ActionProbsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xd0\x01\n" +
	"\x10RiskModelRequest\x12\x1d\n" +
	"\n" +
	"model_type\x18\x01 \x01(\tR\tmodelType\x12!\n" +
	"\freturns_data\x18\x02 \x01(\fR\vreturnsData\x12?\n" +
	"\x06params\x18\x03 \x03(\v2'.quantflow.RiskModelRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\x11RiskModelResponse\x12\x1f\n" +
	"\vresult_data\x18\x01 \x01(\fR\n" +
	"resultData\x12C\n" +
	"\ametrics\x18\x02 \x03(\v2).quantflow.RiskModelResponse.MetricsEntryR\ametrics\x12&\n" +
	"\x0fcompute_time_ms\x18\x03 \x01(\x03R\rcomputeTimeMs\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\xee\x03\n" +
	"\tMLService\x12:\n" +
	"\x05Train\x12\x17.quantflow.TrainRequest\x1a\x18.quantflow.TrainResponse\x12@\n" +
	"\aPredict\x12\x19.quantflow.PredictRequest\x1a\x1a.quantflow.PredictResponse\x12C\n" +
	"\bEvaluate\x12\x1a.quantflow.EvaluateRequest\x1a\x1b.quantflow.EvaluateResponse\x12L\n" +
	"\vAlphaMining\x12\x1d.quantflow.AlphaMiningRequest\x1a\x1e.quantflow.AlphaMiningResponse\x12@\n" +
	"\aRLTrain\x12\x19.quantflow.RLTrainRequest\x1a\x18.quantflow.RLTrainUpdate0\x01\x12F\n" +
	"\tRLPredict\x12\x1b.quantflow.RLPredictRequest\x1a\x1c.quantflow.RLPredictResponse\x12F\n" +
	"\tRiskModel\x12\x1b.quantflow.RiskModelRequest\x1a\x1c.quantflow.RiskModelResponseB'Z%quantflow/internal/python/proto;protob\x06proto3"

var (
	file_ml_proto_rawDescOnce sync.Once
	file_ml_proto_rawDescData []byte
)

func file_ml_proto_rawDescGZIP() []byte {
	file_ml_proto_rawDescOnce.Do(func() {
		file_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_proto_rawDesc), len(file_ml_proto_rawDesc)))
	})
	return file_ml_proto_rawDescData
}

var file_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ml_proto_goTypes = []any{
	(*TrainRequest)(nil),        // 0: quantflow.TrainRequest
	(*TrainResponse)(nil),       // 1: quantflow.TrainResponse
	(*FeatureImportance)(nil),   // 2: quantflow.FeatureImportance
	(*PredictRequest)(nil),      // 3: quantflow.PredictRequest
	(*PredictResponse)(nil),     // 4: quantflow.PredictResponse
	(*EvaluateRequest)(nil),     // 5: quantflow.EvaluateRequest
	(*EvaluateResponse)(nil),    // 6: quantflow.EvaluateResponse
	(*AlphaMiningRequest)(nil),  // 7: quantflow.AlphaMiningRequest
	(*AlphaMiningResponse)(nil), // 8: quantflow.AlphaMiningResponse
	(*DiscoveredFactor)(nil),    // 9: quantflow.DiscoveredFactor
	(*RLTrainRequest)(nil),      // 10: quantflow.RLTrainRequest
	(*RLTrainUpdate)(nil),       // 11: quantflow.RLTrainUpdate
	(*RLPredictRequest)(nil),    // 12: quantflow.RLPredictRequest
	(*RLPredictResponse)(nil),   // 13: quantflow.RLPredictResponse
	(*RiskModelRequest)(nil),    // 14: quantflow.RiskModelRequest
	(*RiskModelResponse)(nil),   // 15: quantflow.RiskModelResponse
	nil,                         // 16: quantflow.TrainRequest.HyperparamsEntry
	nil,                         // 17: quantflow.TrainResponse.MetricsEntry
	nil,                         // 18: quantflow.EvaluateResponse.MetricsEntry
	nil,                         // 19: quantflow.RLTrainRequest.HyperparamsEntry
	nil,                         // 20: quantflow.RLPredictResponse.ActionProbsEntry
	nil,                         // 21: quantflow.RiskModelRequest.ParamsEntry
	nil,                         // 22: quantflow.RiskModelResponse.MetricsEntry
}
var file_ml_proto_depIdxs = []int32{
	16, // 0: quantflow.TrainRequest.hyperparams:type_name -> quantflow.TrainRequest.HyperparamsEntry
	17, // 1: quantflow.TrainResponse.metrics:type_name -> quantflow.TrainResponse.MetricsEntry
	2,  // 2: quantflow.TrainResponse.feature_importance:type_name -> quantflow.FeatureImportance
	18, // 3: quantflow.EvaluateResponse.metrics:type_name -> quantflow.EvaluateResponse.MetricsEntry
	9,  // 4: quantflow.AlphaMiningResponse.factors:type_name -> quantflow.DiscoveredFactor
	19, // 5: quantflow.RLTrainRequest.hyperparams:type_name -> quantflow.RLTrainRequest.HyperparamsEntry
	20, // 6: quantflow.RLPredictResponse.action_probs:type_name -> quantflow.RLPredictResponse.ActionProbsEntry
	21, // 7: quantflow.RiskModelRequest.params:type_name -> quantflow.RiskModelRequest.ParamsEntry
	22, // 8: quantflow.RiskModelResponse.metrics:type_name -> quantflow.RiskModelResponse.MetricsEntry
	0,  // 9: quantflow.MLService.Train:input_type -> quantflow.TrainRequest
	3,  // 10: quantflow.MLService.Predict:input_type -> quantflow.PredictRequest
	5,  // 11: quantflow.MLService.Evaluate:input_type -> quantflow.EvaluateRequest
	7,  // 12: quantflow.MLService.AlphaMining:input_type -> quantflow.AlphaMiningRequest
	10, // 13: quantflow.MLService.RLTrain:input_type -> quantflow.RLTrainRequest
	12, // 14: quantflow.MLService.RLPredict:input_type -> quantflow.RLPredictRequest
	14, // 15: quantflow.MLService.RiskModel:input_type -> quantflow.RiskModelRequest
	1,  // 16: quantflow.MLService.Train:output_type -> quantflow.TrainResponse
	4,  // 17: quantflow.MLService.Predict:output_type -> quantflow.PredictResponse
	6,  // 18: quantflow.MLService.Evaluate:output_type -> quantflow.EvaluateResponse
	8,  // 19: quantflow.MLService.AlphaMining:output_type -> quantflow.AlphaMiningResponse
	11, // 20: quantflow.MLService.RLTrain:output_type -> quantflow.RLTrainUpdate
	13, // 21: quantflow.MLService.RLPredict:output_type -> quantflow.RLPredictResponse
	15, // 22: quantflow.MLService.RiskModel:output_type -> quantflow.RiskModelResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ml_proto_init() }
func file_ml_proto_init() {
	if File_ml_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_proto_rawDesc), len(file_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_proto_goTypes,
		DependencyIndexes: file_ml_proto_depIdxs,
		MessageInfos:      file_ml_proto_msgTypes,
	}.Build()
	File_ml_proto = out.File
	file_ml_proto_goTypes = nil
	file_ml_proto_depIdxs = nil
}
