// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: ml.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLService_Train_FullMethodName       = "/quantflow.MLService/Train"
	MLService_Predict_FullMethodName     = "/quantflow.MLService/Predict"
	MLService_Evaluate_FullMethodName    = "/quantflow.MLService/Evaluate"
	MLService_AlphaMining_FullMethodName = "/quantflow.MLService/AlphaMining"
	MLService_RLTrain_FullMethodName     = "/quantflow.MLService/RLTrain"
	MLService_RLPredict_FullMethodName   = "/quantflow.MLService/RLPredict"
	MLService_RiskModel_FullMethodName   = "/quantflow.MLService/RiskModel"
)

// MLServiceClient is the client API for MLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MLService provides machine learning model training and inference.
type MLServiceClient interface {
	Train(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error)
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	AlphaMining(ctx context.Context, in *AlphaMiningRequest, opts ...grpc.CallOption) (*AlphaMiningResponse, error)
	RLTrain(ctx context.Context, in *RLTrainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RLTrainUpdate], error)
	RLPredict(ctx context.Context, in *RLPredictRequest, opts ...grpc.CallOption) (*RLPredictResponse, error)
	RiskModel(ctx context.Context, in *RiskModelRequest, opts ...grpc.CallOption) (*RiskModelResponse, error)
}

type mLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLServiceClient(cc grpc.ClientConnInterface) MLServiceClient {
	return &mLServiceClient{cc}
}

func (c *mLServiceClient) Train(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, MLService_Train_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, MLService_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, MLService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) AlphaMining(ctx context.Context, in *AlphaMiningRequest, opts ...grpc.CallOption) (*AlphaMiningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlphaMiningResponse)
	err := c.cc.Invoke(ctx, MLService_AlphaMining_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) RLTrain(ctx context.Context, in *RLTrainRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RLTrainUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MLService_ServiceDesc.Streams[0], MLService_RLTrain_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RLTrainRequest, RLTrainUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLService_RLTrainClient = grpc.ServerStreamingClient[RLTrainUpdate]

func (c *mLServiceClient) RLPredict(ctx context.Context, in *RLPredictRequest, opts ...grpc.CallOption) (*RLPredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RLPredictResponse)
	err := c.cc.Invoke(ctx, MLService_RLPredict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) RiskModel(ctx context.Context, in *RiskModelRequest, opts ...grpc.CallOption) (*RiskModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskModelResponse)
	err := c.cc.Invoke(ctx, MLService_RiskModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLServiceServer is the server API for MLService service.
// All implementations must embed UnimplementedMLServiceServer
// for forward compatibility.
//
// MLService provides machine learning model training and inference.
type MLServiceServer interface {
	Train(context.Context, *TrainRequest) (*TrainResponse, error)
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	AlphaMining(context.Context, *AlphaMiningRequest) (*AlphaMiningResponse, error)
	RLTrain(*RLTrainRequest, grpc.ServerStreamingServer[RLTrainUpdate]) error
	RLPredict(context.Context, *RLPredictRequest) (*RLPredictResponse, error)
	RiskModel(context.Context, *RiskModelRequest) (*RiskModelResponse, error)
	mustEmbedUnimplementedMLServiceServer()
}

// UnimplementedMLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLServiceServer struct{}

func (UnimplementedMLServiceServer) Train(context.Context, *TrainRequest) (*TrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Train not implemented")
}
func (UnimplementedMLServiceServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedMLServiceServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedMLServiceServer) AlphaMining(context.Context, *AlphaMiningRequest) (*AlphaMiningResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AlphaMining not implemented")
}
func (UnimplementedMLServiceServer) RLTrain(*RLTrainRequest, grpc.ServerStreamingServer[RLTrainUpdate]) error {
	return status.Error(codes.Unimplemented, "method RLTrain not implemented")
}
func (UnimplementedMLServiceServer) RLPredict(context.Context, *RLPredictRequest) (*RLPredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RLPredict not implemented")
}
func (UnimplementedMLServiceServer) RiskModel(context.Context, *RiskModelRequest) (*RiskModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RiskModel not implemented")
}
func (UnimplementedMLServiceServer) mustEmbedUnimplementedMLServiceServer() {}
func (UnimplementedMLServiceServer) testEmbeddedByValue()                   {}

// UnsafeMLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLServiceServer will
// result in compilation errors.
type UnsafeMLServiceServer interface {
	mustEmbedUnimplementedMLServiceServer()
}

func RegisterMLServiceServer(s grpc.ServiceRegistrar, srv MLServiceServer) {
	// If the following call panics, it indicates UnimplementedMLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLService_ServiceDesc, srv)
}

func _MLService_Train_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).Train(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_Train_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).Train(ctx, req.(*TrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_AlphaMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlphaMiningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).AlphaMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_AlphaMining_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).AlphaMining(ctx, req.(*AlphaMiningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_RLTrain_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RLTrainRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MLServiceServer).RLTrain(m, &grpc.GenericServerStream[RLTrainRequest, RLTrainUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MLService_RLTrainServer = grpc.ServerStreamingServer[RLTrainUpdate]

func _MLService_RLPredict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RLPredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).RLPredict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_RLPredict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).RLPredict(ctx, req.(*RLPredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_RiskModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).RiskModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLService_RiskModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).RiskModel(ctx, req.(*RiskModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLService_ServiceDesc is the grpc.ServiceDesc for MLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quantflow.MLService",
	HandlerType: (*MLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Train",
			Handler:    _MLService_Train_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _MLService_Predict_Handler,
		},
		{
			MethodName: "Evaluate",
			Handler:    _MLService_Evaluate_Handler,
		},
		{
			MethodName: "AlphaMining",
			Handler:    _MLService_AlphaMining_Handler,
		},
		{
			MethodName: "RLPredict",
			Handler:    _MLService_RLPredict_Handler,
		},
		{
			MethodName: "RiskModel",
			Handler:    _MLService_RiskModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RLTrain",
			Handler:       _MLService_RLTrain_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ml.proto",
}
