// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: sentiment.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SentimentService_AnalyzeSentiment_FullMethodName      = "/quantflow.SentimentService/AnalyzeSentiment"
	SentimentService_BatchAnalyzeSentiment_FullMethodName = "/quantflow.SentimentService/BatchAnalyzeSentiment"
)

// SentimentServiceClient is the client API for SentimentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SentimentService provides NLP sentiment analysis for financial text content.
// Supports analysis of news articles, social media posts, earnings call transcripts,
// and other financial text sources for stocks across A-share, HK, US, and crypto markets.
type SentimentServiceClient interface {
	// AnalyzeSentiment analyzes a single text content for sentiment.
	AnalyzeSentiment(ctx context.Context, in *AnalyzeSentimentRequest, opts ...grpc.CallOption) (*AnalyzeSentimentResponse, error)
	// BatchAnalyzeSentiment performs sentiment analysis across multiple symbols.
	BatchAnalyzeSentiment(ctx context.Context, in *BatchAnalyzeRequest, opts ...grpc.CallOption) (*BatchAnalyzeResponse, error)
}

type sentimentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSentimentServiceClient(cc grpc.ClientConnInterface) SentimentServiceClient {
	return &sentimentServiceClient{cc}
}

func (c *sentimentServiceClient) AnalyzeSentiment(ctx context.Context, in *AnalyzeSentimentRequest, opts ...grpc.CallOption) (*AnalyzeSentimentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeSentimentResponse)
	err := c.cc.Invoke(ctx, SentimentService_AnalyzeSentiment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sentimentServiceClient) BatchAnalyzeSentiment(ctx context.Context, in *BatchAnalyzeRequest, opts ...grpc.CallOption) (*BatchAnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchAnalyzeResponse)
	err := c.cc.Invoke(ctx, SentimentService_BatchAnalyzeSentiment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SentimentServiceServer is the server API for SentimentService service.
// All implementations must embed UnimplementedSentimentServiceServer
// for forward compatibility.
//
// SentimentService provides NLP sentiment analysis for financial text content.
// Supports analysis of news articles, social media posts, earnings call transcripts,
// and other financial text sources for stocks across A-share, HK, US, and crypto markets.
type SentimentServiceServer interface {
	// AnalyzeSentiment analyzes a single text content for sentiment.
	AnalyzeSentiment(context.Context, *AnalyzeSentimentRequest) (*AnalyzeSentimentResponse, error)
	// BatchAnalyzeSentiment performs sentiment analysis across multiple symbols.
	BatchAnalyzeSentiment(context.Context, *BatchAnalyzeRequest) (*BatchAnalyzeResponse, error)
	mustEmbedUnimplementedSentimentServiceServer()
}

// UnimplementedSentimentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSentimentServiceServer struct{}

func (UnimplementedSentimentServiceServer) AnalyzeSentiment(context.Context, *AnalyzeSentimentRequest) (*AnalyzeSentimentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeSentiment not implemented")
}
func (UnimplementedSentimentServiceServer) BatchAnalyzeSentiment(context.Context, *BatchAnalyzeRequest) (*BatchAnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchAnalyzeSentiment not implemented")
}
func (UnimplementedSentimentServiceServer) mustEmbedUnimplementedSentimentServiceServer() {}
func (UnimplementedSentimentServiceServer) testEmbeddedByValue()                          {}

// UnsafeSentimentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SentimentServiceServer will
// result in compilation errors.
type UnsafeSentimentServiceServer interface {
	mustEmbedUnimplementedSentimentServiceServer()
}

func RegisterSentimentServiceServer(s grpc.ServiceRegistrar, srv SentimentServiceServer) {
	// If the following call panics, it indicates UnimplementedSentimentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SentimentService_ServiceDesc, srv)
}

func _SentimentService_AnalyzeSentiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeSentimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentimentServiceServer).AnalyzeSentiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentimentService_AnalyzeSentiment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentimentServiceServer).AnalyzeSentiment(ctx, req.(*AnalyzeSentimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SentimentService_BatchAnalyzeSentiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SentimentServiceServer).BatchAnalyzeSentiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SentimentService_BatchAnalyzeSentiment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SentimentServiceServer).BatchAnalyzeSentiment(ctx, req.(*BatchAnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SentimentService_ServiceDesc is the grpc.ServiceDesc for SentimentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SentimentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quantflow.SentimentService",
	HandlerType: (*SentimentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeSentiment",
			Handler:    _SentimentService_AnalyzeSentiment_Handler,
		},
		{
			MethodName: "BatchAnalyzeSentiment",
			Handler:    _SentimentService_BatchAnalyzeSentiment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sentiment.proto",
}
