// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: sentiment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeSentimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TextContent   string                 `protobuf:"bytes,2,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	TextType      string                 `protobuf:"bytes,3,opt,name=text_type,json=textType,proto3" json:"text_type,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	MaxSources    int32                  `protobuf:"varint,5,opt,name=max_sources,json=maxSources,proto3" json:"max_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSentimentRequest) Reset() {
	*x = AnalyzeSentimentRequest{}
	mi := &file_sentiment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSentimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSentimentRequest) ProtoMessage() {}

func (x *AnalyzeSentimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSentimentRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeSentimentRequest) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeSentimentRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AnalyzeSentimentRequest) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *AnalyzeSentimentRequest) GetTextType() string {
	if x != nil {
		return x.TextType
	}
	return ""
}

func (x *AnalyzeSentimentRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AnalyzeSentimentRequest) GetMaxSources() int32 {
	if x != nil {
		return x.MaxSources
	}
	return 0
}

type SentimentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Keywords      []string               `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Entities      []string               `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentimentResult) Reset() {
	*x = SentimentResult{}
	mi := &file_sentiment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentimentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentResult) ProtoMessage() {}

func (x *SentimentResult) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentResult.ProtoReflect.Descriptor instead.
func (*SentimentResult) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{1}
}

func (x *SentimentResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SentimentResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SentimentResult) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SentimentResult) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *SentimentResult) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SentimentResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type AnalyzeSentimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OverallScore  float64                `protobuf:"fixed64,2,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	OverallLabel  string                 `protobuf:"bytes,3,opt,name=overall_label,json=overallLabel,proto3" json:"overall_label,omitempty"`
	Results       []*SentimentResult     `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	ComputeTimeMs float64                `protobuf:"fixed64,5,opt,name=compute_time_ms,json=computeTimeMs,proto3" json:"compute_time_ms,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSentimentResponse) Reset() {
	*x = AnalyzeSentimentResponse{}
	mi := &file_sentiment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSentimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSentimentResponse) ProtoMessage() {}

func (x *AnalyzeSentimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSentimentResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeSentimentResponse) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeSentimentResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AnalyzeSentimentResponse) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *AnalyzeSentimentResponse) GetOverallLabel() string {
	if x != nil {
		return x.OverallLabel
	}
	return ""
}

func (x *AnalyzeSentimentResponse) GetResults() []*SentimentResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *AnalyzeSentimentResponse) GetComputeTimeMs() float64 {
	if x != nil {
		return x.ComputeTimeMs
	}
	return 0
}

func (x *AnalyzeSentimentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchAnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	TextType      string                 `protobuf:"bytes,2,opt,name=text_type,json=textType,proto3" json:"text_type,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnalyzeRequest) Reset() {
	*x = BatchAnalyzeRequest{}
	mi := &file_sentiment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnalyzeRequest) ProtoMessage() {}

func (x *BatchAnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnalyzeRequest.ProtoReflect.Descriptor instead.
func (*BatchAnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{3}
}

func (x *BatchAnalyzeRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *BatchAnalyzeRequest) GetTextType() string {
	if x != nil {
		return x.TextType
	}
	return ""
}

func (x *BatchAnalyzeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type BatchAnalyzeResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Responses     []*AnalyzeSentimentResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Error         string                      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnalyzeResponse) Reset() {
	*x = BatchAnalyzeResponse{}
	mi := &file_sentiment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnalyzeResponse) ProtoMessage() {}

func (x *BatchAnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnalyzeResponse.ProtoReflect.Descriptor instead.
func (*BatchAnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{4}
}

func (x *BatchAnalyzeResponse) GetResponses() []*AnalyzeSentimentResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchAnalyzeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_sentiment_proto protoreflect.FileDescriptor

const file_sentiment_proto_rawDesc = "" +
	"\n" +
	"\x0fsentiment.proto\x12\tquantflow\"\xae\x01\n" +
	"\x17AnalyzeSentimentRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\ftext_content\x18\x02 \x01(\tR\vtextContent\x12\x1b\n" +
	"\ttext_type\x18\x03 \x01(\tR\btextType\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1f\n" +
	"\vmax_sources\x18\x05 \x01(\x05R\n" +
	"maxSources\"\xad\x01\n" +
	"\x0fSentimentResult\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bkeywords\x18\x04 \x03(\tR\bkeywords\x12\x1a\n" +
	"\bentities\x18\x05 \x03(\tR\bentities\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\xf0\x01\n" +
	"\x18AnalyzeSentimentResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12#\n" +
	"\roverall_score\x18\x02 \x01(\x01R\foverallScore\x12#\n" +
	"\roverall_label\x18\x03 \x01(\tR\foverallLabel\x124\n" +
	"\aresults\x18\x04 \x03(\v2\x1a.quantflow.SentimentResultR\aresults\x12&\n" +
	"\x0fcompute_time_ms\x18\x05 \x01(\x01R\rcomputeTimeMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"h\n" +
	"\x13BatchAnalyzeRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1b\n" +
	"\ttext_type\x18\x02 \x01(\tR\btextType\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"o\n" +
	"\x14BatchAnalyzeResponse\x12A\n" +
	"\tresponses\x18\x01 \x03(\v2#.quantflow.AnalyzeSentimentResponseR\tresponses\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xc9\x01\n" +
	"\x10SentimentService\x12[\n" +
	"\x10AnalyzeSentiment\x12\".quantflow.AnalyzeSentimentRequest\x1a#.quantflow.AnalyzeSentimentResponse\x12X\n" +
	"\x15BatchAnalyzeSentiment\x12\x1e.quantflow.BatchAnalyzeRequest\x1a\x1f.quantflow.BatchAnalyzeResponseB'Z%quantflow/internal/python/proto;protob\x06proto3"

var (
	file_sentiment_proto_rawDescOnce sync.Once
	file_sentiment_proto_rawDescData []byte
)

func file_sentiment_proto_rawDescGZIP() []byte {
	file_sentiment_proto_rawDescOnce.Do(func() {
		file_sentiment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentiment_proto_rawDesc), len(file_sentiment_proto_rawDesc)))
	})
	return file_sentiment_proto_rawDescData
}

var file_sentiment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sentiment_proto_goTypes = []any{
	(*AnalyzeSentimentRequest)(nil),  // 0: quantflow.AnalyzeSentimentRequest
	(*SentimentResult)(nil),          // 1: quantflow.SentimentResult
	(*AnalyzeSentimentResponse)(nil), // 2: quantflow.AnalyzeSentimentResponse
	(*BatchAnalyzeRequest)(nil),      // 3: quantflow.BatchAnalyzeRequest
	(*BatchAnalyzeResponse)(nil),     // 4: quantflow.BatchAnalyzeResponse
}
var file_sentiment_proto_depIdxs = []int32{
	1, // 0: quantflow.AnalyzeSentimentResponse.results:type_name -> quantflow.SentimentResult
	2, // 1: quantflow.BatchAnalyzeResponse.responses:type_name -> quantflow.AnalyzeSentimentResponse
	0, // 2: quantflow.SentimentService.AnalyzeSentiment:input_type -> quantflow.AnalyzeSentimentRequest
	3, // 3: quantflow.SentimentService.BatchAnalyzeSentiment:input_type -> quantflow.BatchAnalyzeRequest
	2, // 4: quantflow.SentimentService.AnalyzeSentiment:output_type -> quantflow.AnalyzeSentimentResponse
	4, // 5: quantflow.SentimentService.BatchAnalyzeSentiment:output_type -> quantflow.BatchAnalyzeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sentiment_proto_init() }
func file_sentiment_proto_init() {
	if File_sentiment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentiment_proto_rawDesc), len(file_sentiment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentiment_proto_goTypes,
		DependencyIndexes: file_sentiment_proto_depIdxs,
		MessageInfos:      file_sentiment_proto_msgTypes,
	}.Build()
	File_sentiment_proto = out.File
	file_sentiment_proto_goTypes = nil
	file_sentiment_proto_depIdxs = nil
}
