version: '3'

tasks:
  build:frontend:
    summary: Build the frontend
    dir: frontend
    sources:
      - "**/*"
      - exclude: node_modules/**/*
    generates:
      - dist/**/*
    cmds:
      - npm run build -q

  darwin:build:
    summary: Build macOS application
    deps:
      - task: build:frontend
    cmds:
      - go build -o build/quantflow .
