# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\tquantflow\"\xd4\x01\n\x10\x46\x65tchDataRequest\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x11\n\tdata_type\x18\x02 \x01(\t\x12\x0f\n\x07symbols\x18\x03 \x03(\t\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x05 \x01(\t\x12\x37\n\x06params\x18\x06 \x03(\x0b\x32\'.quantflow.FetchDataRequest.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"W\n\x11\x46\x65tchDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x15\n\rfetch_time_ms\x18\x03 \x01(\x03\x12\r\n\x05\x65rror\x18\x04 \x01(\t2U\n\x0b\x44\x61taService\x12\x46\n\tFetchData\x12\x1b.quantflow.FetchDataRequest\x1a\x1c.quantflow.FetchDataResponseB\'Z%quantflow/internal/python/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%quantflow/internal/python/proto;proto'
  _globals['_FETCHDATAREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_FETCHDATAREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_FETCHDATAREQUEST']._serialized_start=26
  _globals['_FETCHDATAREQUEST']._serialized_end=238
  _globals['_FETCHDATAREQUEST_PARAMSENTRY']._serialized_start=193
  _globals['_FETCHDATAREQUEST_PARAMSENTRY']._serialized_end=238
  _globals['_FETCHDATARESPONSE']._serialized_start=240
  _globals['_FETCHDATARESPONSE']._serialized_end=327
  _globals['_DATASERVICE']._serialized_start=329
  _globals['_DATASERVICE']._serialized_end=414
# @@protoc_insertion_point(module_scope)
