# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import factor_pb2 as factor__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in factor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FactorServiceStub:
    """FactorService provides alpha factor computation capabilities.
    Factors are computed in Python using pandas/numpy and returned as protobuf messages.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeFactor = channel.unary_unary(
                '/quantflow.FactorService/ComputeFactor',
                request_serializer=factor__pb2.ComputeFactorRequest.SerializeToString,
                response_deserializer=factor__pb2.ComputeFactorResponse.FromString,
                _registered_method=True)
        self.ComputeFactorBatch = channel.unary_unary(
                '/quantflow.FactorService/ComputeFactorBatch',
                request_serializer=factor__pb2.ComputeFactorBatchRequest.SerializeToString,
                response_deserializer=factor__pb2.ComputeFactorBatchResponse.FromString,
                _registered_method=True)
        self.ListFactors = channel.unary_unary(
                '/quantflow.FactorService/ListFactors',
                request_serializer=factor__pb2.ListFactorsRequest.SerializeToString,
                response_deserializer=factor__pb2.ListFactorsResponse.FromString,
                _registered_method=True)


class FactorServiceServicer:
    """FactorService provides alpha factor computation capabilities.
    Factors are computed in Python using pandas/numpy and returned as protobuf messages.
    """

    def ComputeFactor(self, request, context):
        """Compute a single factor for a universe of symbols.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeFactorBatch(self, request, context):
        """Compute multiple factors in one batch call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFactors(self, request, context):
        """List all available factors with metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FactorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeFactor': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeFactor,
                    request_deserializer=factor__pb2.ComputeFactorRequest.FromString,
                    response_serializer=factor__pb2.ComputeFactorResponse.SerializeToString,
            ),
            'ComputeFactorBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeFactorBatch,
                    request_deserializer=factor__pb2.ComputeFactorBatchRequest.FromString,
                    response_serializer=factor__pb2.ComputeFactorBatchResponse.SerializeToString,
            ),
            'ListFactors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFactors,
                    request_deserializer=factor__pb2.ListFactorsRequest.FromString,
                    response_serializer=factor__pb2.ListFactorsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantflow.FactorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quantflow.FactorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FactorService:
    """FactorService provides alpha factor computation capabilities.
    Factors are computed in Python using pandas/numpy and returned as protobuf messages.
    """

    @staticmethod
    def ComputeFactor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.FactorService/ComputeFactor',
            factor__pb2.ComputeFactorRequest.SerializeToString,
            factor__pb2.ComputeFactorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeFactorBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.FactorService/ComputeFactorBatch',
            factor__pb2.ComputeFactorBatchRequest.SerializeToString,
            factor__pb2.ComputeFactorBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFactors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.FactorService/ListFactors',
            factor__pb2.ListFactorsRequest.SerializeToString,
            factor__pb2.ListFactorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
