# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\tquantflow\"\r\n\x0bPingRequest\"H\n\x0cPingResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x03\"\x12\n\x10GetStatusRequest\"v\n\x0eStatusResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x03\x12\x17\n\x0f\x61\x63tive_requests\x18\x04 \x01(\x05\x12\x11\n\tmemory_mb\x18\x05 \x01(\x03\x32\x8d\x01\n\rHealthService\x12\x37\n\x04Ping\x12\x16.quantflow.PingRequest\x1a\x17.quantflow.PingResponse\x12\x43\n\tGetStatus\x12\x1b.quantflow.GetStatusRequest\x1a\x19.quantflow.StatusResponseB\'Z%quantflow/internal/python/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%quantflow/internal/python/proto;proto'
  _globals['_PINGREQUEST']._serialized_start=27
  _globals['_PINGREQUEST']._serialized_end=40
  _globals['_PINGRESPONSE']._serialized_start=42
  _globals['_PINGRESPONSE']._serialized_end=114
  _globals['_GETSTATUSREQUEST']._serialized_start=116
  _globals['_GETSTATUSREQUEST']._serialized_end=134
  _globals['_STATUSRESPONSE']._serialized_start=136
  _globals['_STATUSRESPONSE']._serialized_end=254
  _globals['_HEALTHSERVICE']._serialized_start=257
  _globals['_HEALTHSERVICE']._serialized_end=398
# @@protoc_insertion_point(module_scope)
