# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in llm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMServiceStub:
    """LLMService provides LLM inference capabilities via streaming gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/quantflow.LLMService/Chat',
                request_serializer=llm__pb2.LLMChatRequest.SerializeToString,
                response_deserializer=llm__pb2.LLMChatResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/quantflow.LLMService/ListModels',
                request_serializer=llm__pb2.LLMListModelsRequest.SerializeToString,
                response_deserializer=llm__pb2.LLMListModelsResponse.FromString,
                _registered_method=True)
        self.CountTokens = channel.unary_unary(
                '/quantflow.LLMService/CountTokens',
                request_serializer=llm__pb2.CountTokensRequest.SerializeToString,
                response_deserializer=llm__pb2.CountTokensResponse.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """LLMService provides LLM inference capabilities via streaming gRPC.
    """

    def Chat(self, request, context):
        """Chat performs a streaming chat completion. Each response carries
        incremental tokens or tool call deltas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """ListModels returns all available LLM models and their capabilities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountTokens(self, request, context):
        """CountTokens returns the token count for a set of messages (for budget management).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=llm__pb2.LLMChatRequest.FromString,
                    response_serializer=llm__pb2.LLMChatResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=llm__pb2.LLMListModelsRequest.FromString,
                    response_serializer=llm__pb2.LLMListModelsResponse.SerializeToString,
            ),
            'CountTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.CountTokens,
                    request_deserializer=llm__pb2.CountTokensRequest.FromString,
                    response_serializer=llm__pb2.CountTokensResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantflow.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quantflow.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """LLMService provides LLM inference capabilities via streaming gRPC.
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/quantflow.LLMService/Chat',
            llm__pb2.LLMChatRequest.SerializeToString,
            llm__pb2.LLMChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.LLMService/ListModels',
            llm__pb2.LLMListModelsRequest.SerializeToString,
            llm__pb2.LLMListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.LLMService/CountTokens',
            llm__pb2.CountTokensRequest.SerializeToString,
            llm__pb2.CountTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
