# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import ml_pb2 as ml__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub:
    """MLService provides machine learning model training and inference.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
                '/quantflow.MLService/Train',
                request_serializer=ml__pb2.TrainRequest.SerializeToString,
                response_deserializer=ml__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/quantflow.MLService/Predict',
                request_serializer=ml__pb2.PredictRequest.SerializeToString,
                response_deserializer=ml__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/quantflow.MLService/Evaluate',
                request_serializer=ml__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=ml__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.AlphaMining = channel.unary_unary(
                '/quantflow.MLService/AlphaMining',
                request_serializer=ml__pb2.AlphaMiningRequest.SerializeToString,
                response_deserializer=ml__pb2.AlphaMiningResponse.FromString,
                _registered_method=True)
        self.RLTrain = channel.unary_stream(
                '/quantflow.MLService/RLTrain',
                request_serializer=ml__pb2.RLTrainRequest.SerializeToString,
                response_deserializer=ml__pb2.RLTrainUpdate.FromString,
                _registered_method=True)
        self.RLPredict = channel.unary_unary(
                '/quantflow.MLService/RLPredict',
                request_serializer=ml__pb2.RLPredictRequest.SerializeToString,
                response_deserializer=ml__pb2.RLPredictResponse.FromString,
                _registered_method=True)
        self.RiskModel = channel.unary_unary(
                '/quantflow.MLService/RiskModel',
                request_serializer=ml__pb2.RiskModelRequest.SerializeToString,
                response_deserializer=ml__pb2.RiskModelResponse.FromString,
                _registered_method=True)


class MLServiceServicer:
    """MLService provides machine learning model training and inference.
    """

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlphaMining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RLTrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RLPredict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RiskModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=ml__pb2.TrainRequest.FromString,
                    response_serializer=ml__pb2.TrainResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ml__pb2.PredictRequest.FromString,
                    response_serializer=ml__pb2.PredictResponse.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=ml__pb2.EvaluateRequest.FromString,
                    response_serializer=ml__pb2.EvaluateResponse.SerializeToString,
            ),
            'AlphaMining': grpc.unary_unary_rpc_method_handler(
                    servicer.AlphaMining,
                    request_deserializer=ml__pb2.AlphaMiningRequest.FromString,
                    response_serializer=ml__pb2.AlphaMiningResponse.SerializeToString,
            ),
            'RLTrain': grpc.unary_stream_rpc_method_handler(
                    servicer.RLTrain,
                    request_deserializer=ml__pb2.RLTrainRequest.FromString,
                    response_serializer=ml__pb2.RLTrainUpdate.SerializeToString,
            ),
            'RLPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.RLPredict,
                    request_deserializer=ml__pb2.RLPredictRequest.FromString,
                    response_serializer=ml__pb2.RLPredictResponse.SerializeToString,
            ),
            'RiskModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RiskModel,
                    request_deserializer=ml__pb2.RiskModelRequest.FromString,
                    response_serializer=ml__pb2.RiskModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantflow.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quantflow.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService:
    """MLService provides machine learning model training and inference.
    """

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.MLService/Train',
            ml__pb2.TrainRequest.SerializeToString,
            ml__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.MLService/Predict',
            ml__pb2.PredictRequest.SerializeToString,
            ml__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.MLService/Evaluate',
            ml__pb2.EvaluateRequest.SerializeToString,
            ml__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlphaMining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.MLService/AlphaMining',
            ml__pb2.AlphaMiningRequest.SerializeToString,
            ml__pb2.AlphaMiningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RLTrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/quantflow.MLService/RLTrain',
            ml__pb2.RLTrainRequest.SerializeToString,
            ml__pb2.RLTrainUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RLPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.MLService/RLPredict',
            ml__pb2.RLPredictRequest.SerializeToString,
            ml__pb2.RLPredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RiskModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.MLService/RiskModel',
            ml__pb2.RiskModelRequest.SerializeToString,
            ml__pb2.RiskModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
