# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentiment.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sentiment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsentiment.proto\x12\tquantflow\"y\n\x17\x41nalyzeSentimentRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x14\n\x0ctext_content\x18\x02 \x01(\t\x12\x11\n\ttext_type\x18\x03 \x01(\t\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x13\n\x0bmax_sources\x18\x05 \x01(\x05\"w\n\x0fSentimentResult\x12\r\n\x05score\x18\x01 \x01(\x01\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x10\n\x08keywords\x18\x04 \x03(\t\x12\x10\n\x08\x65ntities\x18\x05 \x03(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\"\xad\x01\n\x18\x41nalyzeSentimentResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x15\n\roverall_score\x18\x02 \x01(\x01\x12\x15\n\roverall_label\x18\x03 \x01(\t\x12+\n\x07results\x18\x04 \x03(\x0b\x32\x1a.quantflow.SentimentResult\x12\x17\n\x0f\x63ompute_time_ms\x18\x05 \x01(\x01\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"K\n\x13\x42\x61tchAnalyzeRequest\x12\x0f\n\x07symbols\x18\x01 \x03(\t\x12\x11\n\ttext_type\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"]\n\x14\x42\x61tchAnalyzeResponse\x12\x36\n\tresponses\x18\x01 \x03(\x0b\x32#.quantflow.AnalyzeSentimentResponse\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xc9\x01\n\x10SentimentService\x12[\n\x10\x41nalyzeSentiment\x12\".quantflow.AnalyzeSentimentRequest\x1a#.quantflow.AnalyzeSentimentResponse\x12X\n\x15\x42\x61tchAnalyzeSentiment\x12\x1e.quantflow.BatchAnalyzeRequest\x1a\x1f.quantflow.BatchAnalyzeResponseB\'Z%quantflow/internal/python/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentiment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%quantflow/internal/python/proto;proto'
  _globals['_ANALYZESENTIMENTREQUEST']._serialized_start=30
  _globals['_ANALYZESENTIMENTREQUEST']._serialized_end=151
  _globals['_SENTIMENTRESULT']._serialized_start=153
  _globals['_SENTIMENTRESULT']._serialized_end=272
  _globals['_ANALYZESENTIMENTRESPONSE']._serialized_start=275
  _globals['_ANALYZESENTIMENTRESPONSE']._serialized_end=448
  _globals['_BATCHANALYZEREQUEST']._serialized_start=450
  _globals['_BATCHANALYZEREQUEST']._serialized_end=525
  _globals['_BATCHANALYZERESPONSE']._serialized_start=527
  _globals['_BATCHANALYZERESPONSE']._serialized_end=620
  _globals['_SENTIMENTSERVICE']._serialized_start=623
  _globals['_SENTIMENTSERVICE']._serialized_end=824
# @@protoc_insertion_point(module_scope)
