# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import sentiment_pb2 as proto_dot_sentiment__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/sentiment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentimentServiceStub:
    """SentimentService provides NLP sentiment analysis for financial text content.
    Supports analysis of news articles, social media posts, earnings call transcripts,
    and other financial text sources for stocks across A-share, HK, US, and crypto markets.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/quantflow.SentimentService/AnalyzeSentiment',
                request_serializer=proto_dot_sentiment__pb2.AnalyzeSentimentRequest.SerializeToString,
                response_deserializer=proto_dot_sentiment__pb2.AnalyzeSentimentResponse.FromString,
                _registered_method=True)
        self.BatchAnalyzeSentiment = channel.unary_unary(
                '/quantflow.SentimentService/BatchAnalyzeSentiment',
                request_serializer=proto_dot_sentiment__pb2.BatchAnalyzeRequest.SerializeToString,
                response_deserializer=proto_dot_sentiment__pb2.BatchAnalyzeResponse.FromString,
                _registered_method=True)


class SentimentServiceServicer:
    """SentimentService provides NLP sentiment analysis for financial text content.
    Supports analysis of news articles, social media posts, earnings call transcripts,
    and other financial text sources for stocks across A-share, HK, US, and crypto markets.
    """

    def AnalyzeSentiment(self, request, context):
        """AnalyzeSentiment analyzes a single text content for sentiment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchAnalyzeSentiment(self, request, context):
        """BatchAnalyzeSentiment performs sentiment analysis across multiple symbols.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentimentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=proto_dot_sentiment__pb2.AnalyzeSentimentRequest.FromString,
                    response_serializer=proto_dot_sentiment__pb2.AnalyzeSentimentResponse.SerializeToString,
            ),
            'BatchAnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchAnalyzeSentiment,
                    request_deserializer=proto_dot_sentiment__pb2.BatchAnalyzeRequest.FromString,
                    response_serializer=proto_dot_sentiment__pb2.BatchAnalyzeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantflow.SentimentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quantflow.SentimentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SentimentService:
    """SentimentService provides NLP sentiment analysis for financial text content.
    Supports analysis of news articles, social media posts, earnings call transcripts,
    and other financial text sources for stocks across A-share, HK, US, and crypto markets.
    """

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.SentimentService/AnalyzeSentiment',
            proto_dot_sentiment__pb2.AnalyzeSentimentRequest.SerializeToString,
            proto_dot_sentiment__pb2.AnalyzeSentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchAnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantflow.SentimentService/BatchAnalyzeSentiment',
            proto_dot_sentiment__pb2.BatchAnalyzeRequest.SerializeToString,
            proto_dot_sentiment__pb2.BatchAnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
